# Generated by Django 5.2 on 2026-02-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_client_id_alter_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Trade License', 'Trade License'), ('MOA', 'MOA'), ('Passport', 'Passport'), ('Visa', 'Visa')], max_length=50),
        ),
    ]
